<?php

/**
 * @file
 * contactus.module
 */

// 50 items per page.
define('TOTAL_ITEMS_PER_PAGE_CONTACT', 50);

// Admin uri links.
define('ADMIN_CONTENT_CONTACTUS_MANAGE_URI', '/admin/content/contactus/manage/');
define('ADMIN_CONTENT_CONTACTUS_EDIT_URI', 'admin/content/contact/edit/');
define('ADMIN_CONTENT_CONTACTUS_URI', '/admin/content/contactus');

/**
 * Implements hook_entity_info().
 */
function contactus_entity_info() {
    $contactus_entity_info['contactus'] = array(
        'label' => t('Contact Us'),
        'label callback' => 'contactus_label_callback',
        'entity class' => 'contactus',
        'controller class' => 'contactController',
        'base table' => 'contactus',
        'uri callback' => 'contactus_uri',
        'fieldable' => TRUE,
        'entity keys' => array(
            'id' => 'contact_id',
        ),
        'uri callback' => 'entity_class_uri',
        'load hook' => 'contactus_load',
        'static cache' => TRUE,
         'admin ui' => array(
      'path' => 'admin/content/contactus',
      'controller class' => 'contactusUIController',
      'file' => 'includes/contactus.admin.inc',
    ),
        'module' => 'contactus',
        'access callback' => 'contactus_access_callback',
        'bundles' => array(
            'contact' => array(
                'label' => 'Contacts',
                'admin' => array(
                    'path' => 'admin/structure/contact/manage',
                    'access arguments' => array('administer contact'),
                ),
            ),
        ),
        'views controller class' => 'EntityDefaultViewsController',
    );

    return $contactus_entity_info;
}




function contactus_menu() {
    $items = array();

    $items['contactus/%contactus'] = array(
        'title' => 'Contact Us',
        'page callback' => 'contactus_view_entity',
        'page arguments' => array(1),
        'access callback' => 'contactus_access_menu_callback',
        'access arguments' => array('view', 1),
    );

    $items['contact/locate'] = array(
        'page callback' => 'contact_locate_callback',
        'access arguments' => array('access content'),
    );

    $items['admin/content/contactus/bulk/delete/%'] = array(
        'title' => 'Bulk Delete contacts',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('contactus_bulk_delete', 5),
        'access arguments' => array('administer contact entities'),
        'file' => 'includes/contactus.admin.inc',
    );

    $items['admin/structure/contactus'] = array(
        'title' => 'contactus Fields',
        'access arguments' => array('administer contact entities'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}



/**
 * Implements hook_theme().
 */
function contactus_theme() {
    return array(
        'contactus_full' => array(
            'variables' => array('contact' => NULL),
            'file' => 'includes/contactus.theme.inc',
        ),
    );
}





/**
 * Check access permission for Lawmakers Entity UI.
 */
function contactus_access_menu_callback($op, $lawmakers = NULL, $account = NULL) {
    switch ($op) {
        case 'view':
            return user_access('view contact entities', $account);

        case 'create':
            return user_access('create contact entities', $account);

        case 'update':
            return user_access('edit contact entities', $account);

        case 'delete':
            return user_access('delete contact entities', $account);
    }

    return FALSE;
}





/**
 * Help function api data.
 */
function contact_locate_callback() {

    $params = drupal_get_query_parameters();

    if (isset($params['state'])) {
        $conditions = $params['state'];
        $result = contactus_entity_query($conditions);
        $data = contactus_load_multiple($result);
        drupal_json_output($data);
    }
    elseif (isset($params['party']) && isset($params['chamber'])) {
        $chamber = array('title' => $params['chamber']);
        $party = array('party' => $params['party']);
        $conditions = array_merge($party, $chamber);
        $result = contactus_entity_query($conditions);
        $data = contactus_load_multiple($result);
        drupal_json_output($data);
    }

}





/**
 * Custom controller for the lawmakers entity.
 */
class contactController extends EntityAPIController {

    /**
     * Override the save method.
     */
    public function save($entity, DatabaseTransaction $transaction = NULL) {
        if (isset($entity->is_new)) {
            $entity->created = REQUEST_TIME;
        }

        $entity->changed = REQUEST_TIME;
        return parent::save($entity, $transaction);
    }
}


function contactus_access_callback() {
    if (user_is_anonymous() && !user_access('administer Contactus entities')) {
        return FALSE;
    }
    else {
        return TRUE;
    }
}

function contactus_permission() {
    return array(
        'administer Contactus entities' => array(
            'title' => t('Administer contact us Entities'),
            'description' => t('Allows a user to administer contact us entities'),
        ),
        'view contact entities' => array(
            'title' => t('View contact Entity'),
            'description' => t('Allows a user to view the contact entities.'),
        ),

    );
}


/**
 * Custom controller for the administrator UI.
 */
class contactusUIController extends EntityDefaultUIController {

    /**
     * Override the menu hook for default ui controller.
     */
    public function hook_menu() {
        $items = parent::hook_menu();
        $items[$this->path]['title'] = t('Contact us');
        $items[$this->path]['description'] = t('Manage Contact us, including fields.');
        $items[$this->path]['access callback'] = 'contactus_access_callback';
        $items[$this->path]['access arguments'] = array('administer Contact us entities');
        $items[$this->path]['type'] = MENU_LOCAL_TASK;
        return $items;
    }

    /**
     * Admin form for searching and doing bulk operations.
     */
    public function overviewForm($form, &$form_state) {
        $form['pager'] = array('#theme' => 'pager');
        //echo 656;

        $header = array(
            'contact_id' => array('data' => t('Contact  ID'), 'field' => 'contact_id'),
            'first_name' => array('data' => t('First Name'), 'field' => 'first_name'),
            'last_name' => array('data' => t('last name'), 'field' => 'last_name'),
            'operations' => array('data' => t('Operations'), 'field' => 'operations'),
        );

        $options = array();
        $search_term = !empty($_GET['search']) ? $_GET['search'] : NULL;

        $query = new EntityFieldQuery();
        $query
            ->entityCondition('entity_type', 'contactus');

        if (!empty($search_term)) {
            $query->propertyCondition('first_name', '%' . $search_term . '%', 'like');
        }
        // Check for sort order and sort key.
        if (!empty($_GET['sort']) && !empty($_GET['order'])) {
            $sort = strtoupper($_GET['sort']);
            $order = strtolower($_GET['order']);
            $order = str_replace(' ', '_', $order);
            if ($order != 'operations') {
                $query->propertyOrderBy($order, $sort);
            }
        }

        $query->pager(TOTAL_ITEMS_PER_PAGE_CONTACT);

        $result = $query->execute();
        //var_dump($result);
        $contact_results = !empty($result['contactus']) ? $result['contactus'] : array();
        $contactus_array = !empty($contact_results) ? contactus_load_multiple(array_keys($contact_results)) : array();

        //var_dump($contactus_array);
       // exit;
        foreach ($contactus_array as $contact_id => $contactus) {
            $options['contact_id-' . $contact_id] = array(
                'contact_id' => l($contactus->contact_id, 'contactus/' . $contactus->contact_id),
                'first_name' => l($contactus->first_name, 'contactus/' . $contactus->contact_id),
                'last_name' => l($contactus->last_name, 'contactus/' . $contactus->last_name),
                'operations' =>
                    l(t('View'), 'contactus/' . $contactus->contact_id) . ' ' .
                    l(t('Edit'), ADMIN_CONTENT_CONTACTUS_MANAGE_URI . $contact_id ,array('query' => array('destination' => ADMIN_CONTENT_CONTACTUS_MANAGE_URI))) . ' ' .
                    l(t('Delete'), ADMIN_CONTENT_CONTACTUS_MANAGE_URI . $contact_id . '/delete', array('attributes' => array('class' => array('contactus-delete-' . $contactus->contact_id), ), 'query' => array('destination' => ADMIN_CONTENT_CONTACTUS_URI))),
            );
        }

        $form['search'] = array(
            '#type' => 'fieldset',
            '#title' => t('Basic Search'),
            '#collapsible' => TRUE,
            '#collapsed' => !empty($search_term) ? FALSE : TRUE,
        );

        $form['search']['search_text'] = array(
            '#type' => 'textfield',
            '#title' => t('Search Term'),
            '#default_value' => !empty($search_term) ? $search_term : '',
        );

        $form['search']['search_submit'] = array(
            '#type' => 'submit',
            '#value' => t('Search'),
        );

        $form['bulk_operations'] = array(
            '#type' => 'fieldset',
            '#title' => t('Bulk Operations'),
            '#collapsible' => TRUE,
            '#collapsed' => TRUE,
        );

        $form['bulk_operations']['operations'] = array(
            '#type' => 'select',
            '#options' => array(
                0 => t('Select a bulk operation'),
                'delete' => t('Delete selected lawmakers'),
            ),
        );

        $form['bulk_operations']['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Submit'),
        );

        $form['entities'] = array(
            '#type' => 'tableselect',
            '#header' => $header,
            '#options' => $options,
            '#attributes' => array('class' => array('entity-sort-table')),
            '#empty' => t('There are no lawmakers.'),
        );

        return $form;
    }

    /**
     * Form Submit method.
     */
    public function overviewFormSubmit($form, &$form_state) {
        $values = $form_state['input'];
        $contact_ids = array();

        if (!empty($values['entities'])) {
            foreach ($values['entities'] as $index => $value) {
                if (!empty($value)) {
                    $contact_ids[] = str_replace('$contact_ids-', '', $value);
                }
            }

            switch ($values['operations']) {
                case 'delete':
                    drupal_goto('admin/content/contactus/bulk/delete/' . implode('|', $contact_ids));
                    break;
            }
        }

        if (!empty($values['search_text'])) {
            drupal_goto('admin/content/contactus', array('query' => array('search' => $values['search_text'])));
        }
    }

}




function contactus_entity_query($conditions = array()) {

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'contactus');

    // Apply conditions.
    foreach ($conditions as $key => $value) {
        $query->propertyCondition($key, $value);
    }

    $result = $query->execute();

    if (isset($result['contactus'])) {
        $contact = array_keys($result['contactus']);
    }
    else {
        $contact = array();
    }

    return $contact;
}

/**
 * Label callback for lawmakers entities, for menu router, etc.
 */
function contactus_label_callback($contact, $type) {
    return empty($contact->username) ? 'Untitled Contact' : $contact->first_name;
}

/**
 * Saves Lawmaker to database.
 */
function contactus_save(contactus $contact) {
    return $contact->save();
}



function contactus_view_entity($contact) {
    //echo 5656;
    //exit;
    $fullname = $contact->first_name . ' ' . $contact->last_name;
    drupal_set_title($fullname);
    // Path not entity.
    $contact_output = theme('contactus_full', array('contact' => $contact));
    //var_dump($contact);
    return $contact_output;
}




class contactus extends Entity {
    /**
     * Override defaultUri().
     */
    protected function defaultUri() {
        return array('path' => 'contactus/' . $this->identifier());
    }
}



/**
 * Menu autoloader for /lawmakers.
 */
function contactus_load($contact_id, $reset = FALSE) {
    $contacts = contactus_load_multiple(array($contact_id), array(), $reset);
    return reset($contacts);
}

/**
 * Load multiple lawmakers based on certain conditions.
 */
function contactus_load_multiple($contact_id = array(), $conditions = array(), $reset = FALSE) {
    return entity_load('contactus', $contact_id, $conditions, $reset);
}

/**
 * Deletes a lawmaker.
 */
function contactus_delete(lawmakers $contacts) {
    $contacts->delete();
}

/**
 * Delete multiple lawmakers.
 */
function contactus_delete_multiple(array $contact__ids) {
    //var_dump($contact__ids);
    //exit;

    entity_get_controller('contactus')->delete($contact__ids);
}

